from typing import List

def stations() -> List[str]:
    return [
        "Afrikanische Straße",
        "Alexanderplatz",
        "Alt-Mariendorf"
        "Alt-Tegel",
        "Alt-Tempelhof",
        "Bismarckstraße",
        "Borsigwerke",
        "Bülowstraße",
        "Deutsche Oper",
        "Eberswalder Straße",
        "Ernst-Reuter-Platz",
        "Französische Straße",
        "Friedrichstraße",
        "Gleisdreieck",
        "Hallesches Tor",
        "Hausvogteiplatz",
        "Holzhauser Straße",
        "Kaiserdamm",
        "Kaiserin-Augusta-Straße",
        "Klosterstraße",
        "Kochstraße",
        "Kurt-Schumacher-Platz",
        "Leopoldplatz",
        "Märkisches Museum",
        "Mehringdamm",
        "Mendelssohn-Bartholdy-Park",
        "Mohrenstraße",
        "Naturkundemuseum",
        "Neu-Westend",
        "Nollendorfplatz",
        "Olympia-Stadion",
        "Oranienburger Tor",
        "Otisstraße",
        "Pankow",
        "Paradestraße",
        "Platz der Luftbrücke",
        "Potsdamer Platz",
        "Rehberge",
        "Reinickendorfer Straße",
        "Rosa-Luxemburg-Platz",
        "Ruhleben",
        "Scharnweberstraße",
        "Schönhauser Allee",
        "Schwartzkopffstraße",
        "Seestraße",
        "Senefelderplatz",
        "Sophie-Charlotte-Platz",
        "Spittelmarkt",
        "Stadtmitte",
        "Tempelhof",
        "Theodor-Heuss-Platz",
        "Ullsteinstraße",
        "Vinetastraße",
        "Wedding",
        "Westphalweg",
        "Wittenbergplatz",
        "Zoologischer Garten"
    ]

